// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nhcslyqhkcujmqrnqswm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oY3NseXFoa2N1am1xcm5xc3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwODM1MDYsImV4cCI6MjA5MjY1OTUwNn0.iS-qF5bdb2IyzZZmWoxWTP2DLy4wC_LlZRTAAtO98SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);